### ISSUE TITLE
oursite/oursiteとは

### ISSUE THREAD

**Issue by raiga0310** [Treasure-Hunting/Backend#13]
SSIA

**Comment by Snowman-s** [comment]
Djangoのプロジェクト名をoursiteとしました。で、プロジェクト作成時にDjangoが自動でこのディレクトリを生成します。以上。

注:外のoursiteは変更しても問題ありませんが、中のoursiteの名を変更するとエラーになります。

**Comment by raiga0310** [comment]
実際の挙動においてどんな役割ですか、また、該当ディレクトリが動作に必要のない場合において、消去したときに問題等は生じますか

**Comment by Snowman-s** [comment]
外側のoursiteフォルダから中身を取り出しても動作します。
が、直下には裸のファイルが存在するため、ラップしておくのが丸いと思います。

内側のoursiteフォルダはプロジェクトの情報を持つために必須です。
manage.pyを走らせて動作させるのですが、その際に、まずプロジェクト名のフォルダを参照します。
役割:
1. settings.py 内において、タイムゾーンや言語、動作させるソフトウェア、使用するデータベースなどが定義されています。
2. urls.py 内において、アプリケーションの動作するurlの大きなURLが定義されます(簡単に言えばアプリケーションとプロジェクトの紐づけ)。また、データベース操作を簡単にできるadminを利用できます。

なぜプロジェクトとアプリケーションを分けるのかと言えば、そういう仕様だとしか。

**Comment by Snowman-s** [comment]
[djangoの公式ドキュメント](https://docs.djangoproject.com/ja/2.2/intro/reusable-apps/)によれば、
> すでに mysite/templates を チュートリアル 7 で、 polls/templates を チュートリアル 3 で作成しました。今となっては、なぜテンプレートディレクトリをプロジェクトとアプリケーションに分けたかが明確にわかるかもしれませんね。投票アプリケーションに関する全ては polls にあります。アプリケーションが自己完結していて、新規のプロジェクトにも導入しやすくなっています。

のように、再利用の為だそうです。

**Comment by raiga0310** [comment]
なるほど、仕様なら納得です。ありがとうございます。

**Comment by Siketyan** [comment]
外側が src のほうが分かりやすそうなとこはある

**Comment by Snowman-s** [comment]
僕はそのままの方が情報を漁るときに混乱を招かないと思いますが...。
まぁ、同じフォルダが二回重ねになってるのが気持ち悪いのはもっともです。
だとしても今更変えるのは...どうなの？
