### ISSUE TITLE
CI セットアップ

### ISSUE THREAD

**Issue by Siketyan** [Treasure-Hunting/Backend#18]
CircleCI か Travis CI あたりを使って CI を設定する

- [x] PEP8 で Linter を実行して満たしていない場合は Fail させる
- [x] テストを実行する

**Comment by Snowman-s** [comment]
いまここ。
![image](https://user-images.githubusercontent.com/53784946/64853932-74b49000-d657-11e9-97ca-b7842135b541.png)

**Comment by Siketyan** [comment]
@Snowman-s アクセスを許可しました．

**Comment by Snowman-s** [comment]
僕がやらないほうが早いんじゃ...。
![image](https://user-images.githubusercontent.com/53784946/64869666-c4598280-d67c-11e9-8d04-60c20143ea87.png)
