### ISSUE TITLE
結合テスト

### ISSUE THREAD

**Issue by Snowman-s** [Treasure-Hunting/Backend#30]
- [オープニングからヒントが出るまでの動作を確認] 
- [ヒントが出た後において、オープニングの次の難易度選択をスキップする] 

- [ヒントに対応するキーワードを入れたら次のページに行く] 
- [ヒントの順番はランダムか？ ]
- [キーワードが同じ場合、正しいメッセージ]
- [キーワードが違う場合、エラーメッセージ] 

- [4ページ目を解決したらゴールに誘うページ]
- [Easyなら直接場所が表示され、それ以外ならこれまでのキーワードが表示される] 
- [Normal なら 10進数の対応表を表示] 
- [Hard なら 16進数の対応表を表示]

- [(QRコードで表される)URLに遷移した後に難易度が違うなら違う旨が表示される]  
- [(QRコードで表される)URLに遷移した後に難易度が同じなら2Iクラス展に誘う]
- [プレイヤーが存在しないときの動作(404エラー期待)]

**Comment by Snowman-s** [comment]
ManyToManyFieldだと順番が保存されないんですが...
> player = Player.objects.create(difficulty=difficulty)   
> quizzes = list(difficulty.quizzes.all())  
> shuffle(quizzes)  
> print(quizzes)  
> for i in quizzes:  
> _____player.quizzes.add(i)  
> print(list(player.quizzes.all()))`

-  出力
>  [<Quiz: Quiz object (11)>, <Quiz: Quiz object (10)>, <Quiz: Quiz object (12)>, <Quiz: Quiz object (9)>]
> [<Quiz: Quiz object (9)>, <Quiz: Quiz object (10)>, <Quiz: Quiz object (11)>, <Quiz: Quiz object (12)>]

**Comment by Siketyan** [comment]
@Snowman-s 
あ，そうなんですね．
2 つのモデルをブリッジするモデルを作ってそこにオーダを含める対応でいきましょう．
