### ISSUE TITLE
ドメインの決定および取得

### ISSUE THREAD

**Issue by Siketyan** [Treasure-Hunting/Backend#33]
Related: #31

**Comment by Siketyan** [comment]
Freenom ではすべて空いていました．

![Screenshot_20190916-093925](https://user-images.githubusercontent.com/12772118/64929838-f1b55480-d865-11e9-8ab2-2a3e233cc495.jpg)

**Comment by raiga0310** [comment]
.cfにしようかな、と(@Ark-00 の代理で)
まぁ多分何でもいいとは思いますが

**Comment by Ark-00** [comment]
しけが取りに行ってくれるらしいです。

**Comment by Siketyan** [comment]
`treasure-hunting.tk` を取得しました．
Cloudflare のセットアップも行いました．
