### ISSUE TITLE
SSL/TLS 証明書の取得

### ISSUE THREAD

**Issue by Siketyan** [Treasure-Hunting/Backend#34]

**Comment by Siketyan** [comment]
Cloudflare を使うか， Let's Encrypt などで自前で用意するかですね．

**Comment by Ark-00** [comment]
Cloudflareを使うでいいと思います。

**Comment by Siketyan** [comment]
別で送った PEM を使ってください．

**Comment by Siketyan** [comment]
Close by using Cloudflare Origin Certificate
