### ISSUE TITLE
ファイアウォールの設定

### ISSUE THREAD

**Issue by Siketyan** [Treasure-Hunting/Backend#37]
firewalld や iptables を用いる．

**Comment by Ark-00** [comment]
ufwをつかって、22番ポートと80番ポートと443番ポートを開放して、60000~61000番ポートをudpで開放しました。

**Comment by Siketyan** [comment]
@Ark-00 
一般的にセキュリティ上の理由から SSH でデフォルトの 22 番ポートを使うことは推奨されていません．
また， 60000~61000/udp を開放した理由はなんですか ?
今回のケースでは特に必要ないように思えますが．

**Comment by Ark-00** [comment]
セキュリティ上の理由があるなら、変更します。
特に必要ないんですか...
とりあえず、調べてみて、脳死で開けてました。

**Comment by Siketyan** [comment]
@Ark-00 
必要のないポートを開放することは無駄なセキュリティリスクを増やすことになります．
自分が何をしようとしているかは理解した上で行ってくださいね．

**Comment by Ark-00** [comment]
８０、４４３以外のポートを閉じたまま、諸事情により、通信がタイムアウトして、ｓｓｈで接続できなくなってしまいました…

**Comment by Siketyan** [comment]
@Ark-00
諸事情により，ではなくて SSHd を 22/tcp でリッスンさせたまま 22/tcp を閉じたからじゃないですか ?

**Comment by Ark-00** [comment]
その場合ってどうすればいいんですか？

**Comment by Siketyan** [comment]
@Ark-00 Azure Portal からコンソール接続して復旧させればいいかと思います．

**Comment by Ark-00** [comment]
ありがとうございます。復旧できました。

**Comment by Siketyan** [comment]
@Ark-00 結局 SSH のポート変更は完了しましたか ?
ファイアウォールの管轄ではないと思うので一旦クローズしますね．
