### ISSUE TITLE
tresure -> tre"a"sure

### ISSUE THREAD

**Issue by Snowman-s** [Treasure-Hunting/Backend#45]
全てのタイプミスを直す

**Comment by raiga0310** [comment]
現在開発しているブランチでもスペルミスが発生しています、これはあとですべて一括で直すということでしょうか

**Comment by Snowman-s** [comment]
ええ

**Comment by raiga0310** [comment]
f04e1516b861e69f7f2cb6e95756ff34e241b27f で追加した部分でも、treasureではなくtresureになっているのですが、それはすべての実装が終わったのちにスペルを直すという認識でいいのでしょうか

**Comment by Snowman-s** [comment]
新たにブランチを生やすつもりです。単に仕事は二倍になりますが、そちらの方がブランチがスッキリすると思いまして。

**Comment by Snowman-s** [comment]
ということで今から名前変更するので、終わるまで可能な限りmasterから新しくブランチを生やさないでください。仕事が増えます。

**Comment by raiga0310** [comment]
了解しました
