### ISSUE TITLE
リセット機能の追加

### ISSUE THREAD

**Issue by raiga0310** [Treasure-Hunting/Backend#49]
dif-selにおいて設定した難易度をリセットできる/reset/を追加

**Comment by raiga0310** [comment]
今更ながら二回目以降のリセットの禁止は実装されてますか

**Comment by Snowman-s** [comment]
リセットの回数を記録せねばならないのですか

**Comment by Snowman-s** [comment]
リセットを何回もしたところで不正に進捗をスキップできないので必要ないと判断しました。

**Comment by Snowman-s** [comment]
...がよく考えたらplayer_pkが存在しないのにリセットされた際の対策がありませんね...。

**Comment by raiga0310** [comment]
そのあたりはすぐに実装できますか？
できればお早めに

**Comment by raiga0310** [comment]
まぁ実装しなくてもいいような気もしますが

**Comment by Snowman-s** [comment]
実装しましたので確認してください
