### ISSUE TITLE
QRコード最後に読んだ時のページ

### ISSUE THREAD

**Issue by Snowman-s** [Treasure-Hunting/Backend#5]
/on-goal/
・セッションを読んで難易度の照会をするページ。
	・難易度をURLから得る。(getとかで渡されるもの。)
	・セッションの主キーを読んで、そこからPlayerインスタンスを得る。
	・Playerインスタンスの難易度と、URLから得た難易度が等しいならば、
		・２Ｉクラス展への誘導する表示やその他するページに移行。
	・さもなければ
		・難易度が違うなどの旨を表示する。

**Comment by raiga0310** [comment]
`class OnGoal(TemplateView):
    template_name = 'tresure/on_goal.html'

    def get(self, request, **kwargs):
        player = get_object_or_404(Player,
                                   pk=request.session.get('player_pk', -1))
        if kwargs['pk'] == player.difficulty.pk:
            return HttpResponseRedirect(reverse('tresure:last'))
        return super().get(request, **kwargs)`
これの条件式elseがないのはなぜですか

**Comment by Siketyan** [comment]
@raiga0310 
メソッド内で return した後のコードは実行されないので `else` は取り除くことが多いです．

**Comment by raiga0310** [comment]
なるほど、ありがとうございます。 🙇

**Comment by raiga0310** [comment]
このIssueだと/on-goal/ですが、view.pyのOnGoalクラス内だと’on_goal’なのですが、どちらに統一したほうがいいとかはありますか

**Comment by Snowman-s** [comment]
どこの「on_goal」の事を指していますか

**Comment by raiga0310** [comment]
templetenameのやつ、のはずですが

**Comment by Snowman-s** [comment]
ああ、それは単にtemplates 内のhtmlの場所を表しているだけです。

**Comment by raiga0310** [comment]
あ、いや、ページ名と統一したいなという所存なので、そちらも変えていただけると嬉しいのですが

**Comment by Snowman-s** [comment]
あ、はい。「-」の方に統一かな。今の全てのプルリクエストがマージされてからやります。

**Comment by raiga0310** [comment]
はい、確認しました、ありがとうございます。
