### ISSUE TITLE
ユーザーのページバックの禁止、それに準ずる動作の阻害

### ISSUE THREAD

**Issue by raiga0310** [Treasure-Hunting/Backend#51]
ブラウザの戻るボタンを押す行為によって生じうる不都合などを未然に防ぐための対策を講じる

**Comment by Siketyan** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event

**Comment by raiga0310** [comment]
調べるとJavascriptでの実装例ばかり出ますが、機能を実装する際にjsファイルでもサーバー上で機能するようにすることはできのでしょうか、それともPythonのみしか動かせないのでしょうか

**Comment by Snowman-s** [comment]
通常通りの方法...<script>タグ...で問題なく動作するようです。

**Comment by Snowman-s** [comment]
またはtreasure内にstaticフォルダを作ってその下にjsやcssを入れておき、HTML(template)から {%static%} 文で参照できるようです。

**Comment by raiga0310** [comment]
ではFrontendの方でstaticディレクトリと禁止するためのJSファイルを作りたいと思います(これはここに書くべき事項ではないような気もしますが念のため)
