### ISSUE TITLE
2進数16進数変換表の無限ループの解消

### ISSUE THREAD

**Issue by raiga0310** [Treasure-Hunting/Backend#52]
/go-goal/における変換表の無限ループを解消する

**Comment by raiga0310** [comment]
[utility](https://github.com/Treasure-Hunting/Backend/blob/master/oursite/tresure/utility.py)
内の処理で無限ループが発生しているのではと予想しました。

**Comment by Siketyan** [comment]
今調査しています．

**Comment by Siketyan** [comment]
`ConversionTableResolver.createTable(difficulty_pk)` が static になっているせいか， conversionTable が再利用されており，アクセスのたびにそこに追加していたようです．
