### ISSUE TITLE
404をプレイヤーにとって優しいメッセージにする

### ISSUE THREAD

**Issue by Snowman-s** [Treasure-Hunting/Backend#60]
404エラーのデフォルトのページを表示するだけでは、客が壊れたと誤解する可能性があるため。
(バックキーやURL直打ちさえされなければ、問題ないと思いますが)

**Comment by Snowman-s** [comment]
案:/error-404/ページを増設。
404に遷移する代わりに、そのページにリダイレクトする。

**Comment by Snowman-s** [comment]
この場合、get_object_or_404 が完全に使用不可となるため、何か替わりを考える必要がある。

**Comment by Siketyan** [comment]
リダイレクトしないで 404 ステータスとともに HTML レスポンスを返せばいいのでは ?

**Comment by Snowman-s** [comment]
https://docs.djangoproject.com/ja/2.2/topics/http/views/ こういうことですかね。

**Comment by Snowman-s** [comment]
404.htmlを作成すればいいと。

**Comment by Siketyan** [comment]
https://docs.djangoproject.com/en/2.2/topics/http/views/#customizing-error-views

**Comment by Snowman-s** [comment]
@raiga0310 エラーメッセージを表示する以外の機能は必要ですか？

**Comment by Snowman-s** [comment]
必要なければ404.htmlで簡便に作成したいと思います。

**Comment by raiga0310** [comment]
とりあえずだいじょうぶです

**Comment by Snowman-s** [comment]
フロントエンドに任せた
